[package]
name = "pfen"
version = "1.2.0"
edition = "2021"

description = "A fen parsing library."
authors = ["Kyllingene"]
license = "MIT"
repository = "https://github.com/Kyllingene/pfen"

[dependencies]
thiserror = "1.0.50"

[dev-dependencies]
pretty_assertions = "1"

