[package]
name = "pfen"
version = "1.2.1"
edition = "2021"

description = "A fen parsing library."
authors = ["Kyllingene"]
license = "MIT"
repository = "https://github.com/Kyllingene/pfen"

[dependencies]
thiserror-no-std = "2.0.2"

[dev-dependencies]
pretty_assertions = "1"

